# Generated by Django 4.1.2 on 2022-12-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_category',
            old_name='Vname',
            new_name='Cname',
        ),
    ]
