# Generated by Django 4.1.2 on 2022-12-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_vehicledb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledb',
            old_name='CategoryName',
            new_name='Cname',
        ),
    ]
