# Generated by Django 4.1.2 on 2022-12-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_admindb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admindb',
        ),
    ]
