# Generated by Django 4.1.2 on 2023-01-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_colour_vehicle_category_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindb',
            name='ConfirmPassword',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='UserName',
        ),
    ]
