# Generated by Django 4.1.2 on 2023-01-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_contactdatab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_category',
            name='Brand',
        ),
    ]
